# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build constructed stats


Resources:
    # BuildConstructedDeckStats:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         Handler: legacy/build-constructed-deck-stats.default
    #         Runtime: nodejs16.x
    #         Timeout: 880
    #         CodeUri: ./dist/legacy/build-constructed-deck-stats
    #         MemorySize: 10240
    #         ReservedConcurrentExecutions: 10
    #         Policies:
    #             - AWSLambdaVPCAccessExecutionRole
    #             - AmazonSESFullAccess
    #             - SecretsManagerReadWrite
    #             - AmazonSNSReadOnlyAccess
    #             - AmazonS3FullAccess
    #             - AWSLambda_FullAccess
    #             # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
    #         Tags:
    #             LambdaName: cron-build-constructed-deck-stats
    #         Events:
    #             # Populate the info on the last hour
    #             LastPeriodTrigger:
    #                 Type: Schedule
    #                 Properties:
    #                     # Triggers every 4 hours
    #                     # Schedule: cron(0 4/4 * * ? *)
    #                     Schedule: cron(0 18 * * ? *) # run only once a day to reduce costs
    BuildDailyConstructedDeckStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: daily/build-constructed-deck-stats.default
            Runtime: nodejs16.x
            Timeout: 880
            CodeUri: ./dist/daily/build-constructed-deck-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 10
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-daily-constructed-deck-stats
            Events:
                # Populate the info on the last hour
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0 3 * * ? *)
    AggregateDailyConstructedDeckStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: aggregation/build-aggregated-stats.default
            Runtime: nodejs16.x
            Timeout: 880
            CodeUri: ./dist/aggregation/build-aggregated-stats
            MemorySize: 8000
            ReservedConcurrentExecutions: 10 # Need to investigate locks. To avoid lock races when inserting data in DB
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-aggregate-daily-constructed-deck-stats
            Events:
                # Populate the info on the last hour
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0 5 * * ? *)
    RetrieveConstructedDeckDetails:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve/get-constructed-meta-deck.default
            Runtime: nodejs18.x
            Timeout: 5
            MemorySize: 128
            CodeUri: ./dist/retrieve/get-constructed-meta-deck
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-get-constructed-meta-deck
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE

