# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build constructed stats


Resources:
    BuildHourlyConstructedDeckStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: hourly/build-constructed-deck-stats.default
            Runtime: nodejs16.x
            Timeout: 880
            CodeUri: ./dist/hourly/build-constructed-deck-stats
            MemorySize: 4000
            ReservedConcurrentExecutions: 10
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-hourly-constructed-deck-stats
            Events:
                # Populate the info on the last hour
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        # Cron that runs every hour at 10 minutes past the hour
                        Schedule: cron(10 * * * ? *)
    BuildDailyAggregateDeckStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: daily/_build-daily-aggregate.default
            Runtime: nodejs16.x
            Timeout: 880
            CodeUri: ./dist/daily/_build-daily-aggregate
            MemorySize: 3000
            ReservedConcurrentExecutions: 10
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-daily-aggregate-deck-stats
            Events:
                # Populate the info on the last hour
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        # Cron that runs once a day at 00:10
                        Schedule: cron(10 0 * * ? *)
    AggregateHourlyConstructedDeckStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: final-stats/build-aggregated-stats.default
            Runtime: nodejs16.x
            Timeout: 880
            CodeUri: ./dist/final-stats/build-aggregated-stats
            MemorySize: 5000 # around 566k ms at 63% of 8000
            ReservedConcurrentExecutions: 10 # Need to investigate locks. To avoid lock races when inserting data in DB
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-aggregate-hourly-constructed-deck-stats
                #  TODO: trigger this after the hourly builds have been done, either via direct lambda invocation
                #  or via sqs
            # Events:
            #     LastPeriodTrigger:
            #         Type: Schedule
            #         Properties:
            #             # Cron that runs every hour at 40 minutes past the hour
            #             Schedule: cron(40 * * * ? *)
    RetrieveConstructedDeckDetails:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve/get-constructed-meta-deck.default
            Runtime: nodejs18.x
            Timeout: 5
            MemorySize: 128
            CodeUri: ./dist/retrieve/get-constructed-meta-deck
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-get-constructed-meta-deck
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE

